name: Build and deploy Python project to Azure Function App - purviewblobtrigger
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './purviewblobtrigger'  # Changed this line
  PYTHON_VERSION: '3.10'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r purviewblobtrigger/requirements.txt --target="purviewblobtrigger/.python_packages/lib/site-packages"
          
      - name: Prepare artifact
        run: |
          mkdir -p purviewblobtrigger/.python_packages/lib/python3.10/site-packages
          cp -r purviewblobtrigger/.python_packages/lib/site-packages/* purviewblobtrigger/.python_packages/lib/python3.10/site-packages/

      - name: Zip artifact for deployment
        run: |
          cd purviewblobtrigger && zip -r ../release.zip . \
          --exclude="venv/*" \
          --exclude=".git*" \
          --exclude="*.pyc" \
          --exclude="__pycache__/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
            !.git*
            !*.pyc
            !__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'purviewblobtrigger'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXXXXXXX }} #Will be provided when you connect Azure to Github
          scm-do-build-during-deployment: true
          enable-oryx-build: true
