name: Build and deploy Python project to Azure Function App - pci100
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './pciremediation'
  PYTHON_VERSION: '3.10'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd pciremediation
          python -m pip install --upgrade pip
          # Install to a .python_packages directory
          mkdir -p .python_packages/lib/site-packages
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt
          
      - name: Zip artifact for deployment
        run: |
          cd pciremediation
          zip -r release.zip . -x "venv/*"
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            pciremediation/release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
        
      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_XXXXXXXXX }} #Will be provided when you connect Azure to Github
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_XXXXXXXXX }} #Will be provided when you connect Azure to Github
          subscription-id: ${{ secrets.AZUREAPPSERVICE_XXXXXXXXX }} #Will be provided when you connect Azure to Github
      
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'pci100'
          slot-name: 'Production'
          package: .
      
      - name: 'Restart Function App'
        uses: Azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az functionapp restart --name pci100 --resource-group dlp-solution-rg
            sleep 30
            az functionapp show --name pci100 --resource-group dlp-solution-rg --query state
